### ISSUE TITLE
Support for currency

### ISSUE THREAD

**Issue by davistan** [SteveyPugs/fixy#10]
Hi, we can include something like currency parsing? Eg. 13,300.00

**Comment by SteveyPugs** [comment]
@davistan this could be useful but only on CSV mostly. Parsing back to an object with a dollar sign might not be useful as it might be passed to a front end library that can do currency conversion. Will look into it.

**Comment by SteveyPugs** [comment]
@davistan I've gone ahead and added this. Let me know if this is what you needed!

**Comment by davistan** [comment]
Cool. Thanks.
