### ISSUE TITLE
Fixy throws TypeError when skiplines is undefined

### ISSUE THREAD

**Issue by heyfrench** [SteveyPugs/fixy#18]
The docs say this field is optional, but when omitted a `TypeError` is thrown b/c of the strict `=== null` on line 91 of `fixy/index.js`. Setting `skiplines: null` resolves the issue but is not very obvious. 

An update to the docs would probably suffice, but I think it would be more consistent with other libraries if optional fields could simply be left undefined.

Let me know what approach you prefer and I'll whip up a PR w/ a test case. Thanks a bunch for the library, you've saved me tons of time!

**Comment by SteveyPugs** [comment]
@heyfrench yes this is fine. I was a noob when writing this, you can adjust the code if you would like, PR is more than fine with me. Go for it.

**Comment by SteveyPugs** [comment]
Sorry for the really late response, by the way.

**Comment by heyfrench** [comment]
No worries! Thanks again for writing this. We're putting it through the paces and it's working great.
