### ISSUE TITLE
package.json version bump

### ISSUE THREAD

**Issue by davebriand** [SteveyPugs/fixy#27]
Your merge from 3 months ago isn't added to npm because the version didn't change so errors are still being silenced and console.log'd

I'm assuming this would be a major version bump since it's a breaking change.

**Comment by SteveyPugs** [comment]
My apologies. I will bump this now. I always thought it was based on the git repo.

**Comment by SteveyPugs** [comment]
Ok just published 1.2.0. Let me know if this resolved it.

**Comment by SteveyPugs** [comment]
Closing as this has been done and this is stale.
