### ISSUE TITLE
On float types, "precision" property is incorrectly spelled as "percision"

### ISSUE THREAD

**Issue by mossjm** [SteveyPugs/fixy#30]
This is incorrectly spelled in both the code and the documentation.
The code should probably be updated to support both spellings for backward compatibility.

**Comment by stephen-pugliese** [comment]
Hi @mossjm I will see if I can find time to take care of this, quite busy these days. If you would like to do this in a pull request I am more then happy to approve it.

**Comment by SteveyPugs** [comment]
Hi @mossjm I will see if I can find time to take care of this, quite busy these days. If you would like to do this in a pull request I am more then happy to approve it. (sorry posted it from the wrong account)

**Comment by mossjm** [comment]
I submitted a pull request to fix the code and the documentation.
Would you be able to add a test for me?
Thanks
