### ISSUE TITLE
Date formats

### ISSUE THREAD

**Issue by GaryBoatjump** [SteveyPugs/fixy#33]
What are the date format options available for this type of data? 

Date
type : "date"
name (Required) | Name of the Column
width (Required) | Length of Column
start (Required) | Start of Column in Row
**inputformat (Required) | Format Date Date is Currently In
outputformat (Required) | Format Date Date is Returned As**
level (Required if Multi Level) | Level Map Name

Could you show me an example? Thank you.

**Comment by SteveyPugs** [comment]
Hey @GaryBoatjump anything that is format-able via https://momentjs.com/docs/#/parsing/ is fine.

Example: https://runkit.com/embed/mq1vfozesf2n
