### ISSUE TITLE
automatically calculate field start if not specified

### ISSUE THREAD

**Issue by opensas** [SteveyPugs/fixy#37]
It should assume that all fields are consecutive if start is not specified, could be calculated with the previous field start + width

SO that you should only need to specifiy the name, width and type

If it's ok with you, I might give it a try and send you a PR

**Comment by SteveyPugs** [comment]
Yeah I like that idea. Go for it

**Comment by SteveyPugs** [comment]
@opensas just a note, I did a little repo cleaning of this tonight. ESLint, etc. So if you started coding this, you want to pull the latest master.

**Comment by opensas** [comment]
ok, this is my take at it: https://github.com/SteveyPugs/fixy/pull/41
