### ISSUE TITLE
Vulnerability in moment.js version 2.29.2

### ISSUE THREAD

**Issue by olivercox** [SteveyPugs/fixy#61]
A couple vulnerabilities have been exist in moment.js that are resolved in version 2.29.4

https://github.com/advisories/GHSA-8hfj-j24r-96c4
https://github.com/advisories/GHSA-wc69-rhjr-hc9g

Bumbing the moment.js version 2.29.4 would be really nice.

**Comment by Audarth** [comment]
hey any plans to release this to get rid of the Vulnerability?

**Comment by SteveyPugs** [comment]
Sorry I merged the code I forgot to publish. I’ll get it to tonight

**Comment by SteveyPugs** [comment]
@Audarth it is published now @ 1.3.3 
![image](https://user-images.githubusercontent.com/2607556/182516557-00d6b682-74c4-4133-a221-6db09043e552.png)
